package com.example.demo.enums;

public enum LaboratoryTestName {

    CRP, OB, GlUCOSE, CHOLESTEROL, CREATININE, TRIGLYCERIDES,
    TROPONIN, C_REACTIVE_PROTEIN, UREA, MAGNESIUM, POTASSIUM,
    AMYLASE, LIPASE, TSH, FT3, FT4, PROLACTIN, TESTOSTERONE,
    BILIRUBIN, URIC_ACID

}