package com.example.demo.enums;

public enum MedicalExaminationEnums {

    MEDICAL_CONSULTATION, EEG, EMG, ANGIOGRAPHY, MAGNETIC_RESONANSE,
    COMPUTED_TOMOGRAPHY, GASTROSCOPY, COLONOSCOPY, USG_BELLY, ENDOSCOPY,
    BIOPSY, USG_THYROID, USG_OVARIAN, STOMACH_BIOPSY, SURGICAL_OPERATION,
    THORACOSCOPY, LAPAROSCOPY, USG_EYE, OCT, GONIOSCOPY, EYE_DUPLEX, PACHYMETRY,
    SKIN_BIOPSY, MICROSCOPIC_EXAMINATION, HISTOPATHOLOGICAL_EXAMINATION,
    PATCH_TEST, USG_RENAL, RENAL_BIOPSY, RENAL_SCINTIGRAPHY, RENAL_ANGIOGRAPHY,
    SKIN_TESTS, NUTRITION_TESTS, ALLERGEN_BLOOD_PANEL, TESTS_DETECTING_IgE_SYMPTOMS,
    INHALATION_TESTS, HEART_ULTRASOUND, HOLTER_EKG, ECHOCARDIOGRAM, STRESS_TEST, USG, RTG
}